{
  "formatVersion": "1.1",
  "component": {
    "group": "im.nfc.flutter_nfc_kit",
    "module": "flutter_nfc_kit_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a10d8ac38de835021c8d2f920dbf50a920ccc030"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0.aar",
          "url": "flutter_nfc_kit_release-1.0.0.aar",
          "size": 31531,
          "sha512": "39d948dfbfe0427c8a59088f3f98c3cc3e8b16be7d7ff029c04279cce8cf7c9f7511331d91f5e3178b42d3c24e06d2862418be95ad9d6e60a12956d2765a9142",
          "sha256": "005fa7c87251191df6076c9da0e5cfa02652397d6b64f1a4a2fae45711d553ef",
          "sha1": "15ffb77893dd3860ccf9c2f26533cc72bf074adb",
          "md5": "417929927b31966f0b7aecb0c61fd8ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a10d8ac38de835021c8d2f920dbf50a920ccc030"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0.aar",
          "url": "flutter_nfc_kit_release-1.0.0.aar",
          "size": 31531,
          "sha512": "39d948dfbfe0427c8a59088f3f98c3cc3e8b16be7d7ff029c04279cce8cf7c9f7511331d91f5e3178b42d3c24e06d2862418be95ad9d6e60a12956d2765a9142",
          "sha256": "005fa7c87251191df6076c9da0e5cfa02652397d6b64f1a4a2fae45711d553ef",
          "sha1": "15ffb77893dd3860ccf9c2f26533cc72bf074adb",
          "md5": "417929927b31966f0b7aecb0c61fd8ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0-sources.jar",
          "url": "flutter_nfc_kit_release-1.0.0-sources.jar",
          "size": 8003,
          "sha512": "bba50435c4b3a2fa281b3b379a3a93f45d24871cd4407ca21e505bb09d053910afefb1aaff6828bc300cdedff7fc9bba56664290b382d65d4aae7c73b5ab8cc8",
          "sha256": "00d81fefbd3919a2c09c32fa141afdb2f7fc0a95bf3548d953a8e456e0e7fd0c",
          "sha1": "9662846c10153acb3ce9f7d0a5c1e1ecd3f5e12c",
          "md5": "dbb383583ee3db9c483499c98ba89027"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0-javadoc.jar",
          "url": "flutter_nfc_kit_release-1.0.0-javadoc.jar",
          "size": 291837,
          "sha512": "489d5a4677be53e60e8dfa466537175171c76bab2b5bd45bd2f380de0fcc5a84ac131186337291d6f459f6726c9010b18523a7ad6ebe1e0b44a269cc43dfd0d9",
          "sha256": "bbded8be5dcba45bde018789a2086a7d269defe0c8c15e7c47e303a66c90e054",
          "sha1": "2bc05a738dad2fd8165409af4ae5a2b55510e0de",
          "md5": "e176e0612e2f9206941b03b234d526bf"
        }
      ]
    }
  ]
}
