{
  "formatVersion": "1.1",
  "component": {
    "group": "im.nfc.flutter_nfc_kit",
    "module": "flutter_nfc_kit_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0.aar",
          "url": "flutter_nfc_kit_release-1.0.0.aar",
          "size": 31464,
          "sha512": "381d8b9853f96ee75364efa71f7340d6e666bb4e46df9fd98189d0fff1c583daa23850f33bc7eef520627c54058d97fe26251677641aa482ddfc57f72f7ddf1a",
          "sha256": "ddc67df943c4ca45341531dda7764d7ae28e4249a4457feb420123c4207058e8",
          "sha1": "43ac1b3497aa61949c4a8fdbc55cc2d1f7cce4af",
          "md5": "e21fedceb51508469b1e2b16f68f228c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0.aar",
          "url": "flutter_nfc_kit_release-1.0.0.aar",
          "size": 31464,
          "sha512": "381d8b9853f96ee75364efa71f7340d6e666bb4e46df9fd98189d0fff1c583daa23850f33bc7eef520627c54058d97fe26251677641aa482ddfc57f72f7ddf1a",
          "sha256": "ddc67df943c4ca45341531dda7764d7ae28e4249a4457feb420123c4207058e8",
          "sha1": "43ac1b3497aa61949c4a8fdbc55cc2d1f7cce4af",
          "md5": "e21fedceb51508469b1e2b16f68f228c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0-sources.jar",
          "url": "flutter_nfc_kit_release-1.0.0-sources.jar",
          "size": 8003,
          "sha512": "bba50435c4b3a2fa281b3b379a3a93f45d24871cd4407ca21e505bb09d053910afefb1aaff6828bc300cdedff7fc9bba56664290b382d65d4aae7c73b5ab8cc8",
          "sha256": "00d81fefbd3919a2c09c32fa141afdb2f7fc0a95bf3548d953a8e456e0e7fd0c",
          "sha1": "9662846c10153acb3ce9f7d0a5c1e1ecd3f5e12c",
          "md5": "dbb383583ee3db9c483499c98ba89027"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_nfc_kit_release-1.0.0-javadoc.jar",
          "url": "flutter_nfc_kit_release-1.0.0-javadoc.jar",
          "size": 291837,
          "sha512": "489d5a4677be53e60e8dfa466537175171c76bab2b5bd45bd2f380de0fcc5a84ac131186337291d6f459f6726c9010b18523a7ad6ebe1e0b44a269cc43dfd0d9",
          "sha256": "bbded8be5dcba45bde018789a2086a7d269defe0c8c15e7c47e303a66c90e054",
          "sha1": "2bc05a738dad2fd8165409af4ae5a2b55510e0de",
          "md5": "e176e0612e2f9206941b03b234d526bf"
        }
      ]
    }
  ]
}
