{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.flutter.plugins.nfcmanager",
    "module": "nfc_manager_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "nfc_manager_release-1.0.0.aar",
          "url": "nfc_manager_release-1.0.0.aar",
          "size": 97162,
          "sha512": "4c8366086192d37471461350def70ce461b65ede33116394314cd6dbddc0fb571cb56094e5d8b10e9924c3b04e47634532ca045f180f755cd2b6e1d5355ede17",
          "sha256": "5dafebd3b04c602e451c80a15b2c0dc7288cd3a9b60ed8195e584b4b02711e79",
          "sha1": "7f2c8dd42f5d5c425b7f982359efea08c5404d6d",
          "md5": "dd16a0ec30a363cb465cb2c680567616"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "nfc_manager_release-1.0.0.aar",
          "url": "nfc_manager_release-1.0.0.aar",
          "size": 97162,
          "sha512": "4c8366086192d37471461350def70ce461b65ede33116394314cd6dbddc0fb571cb56094e5d8b10e9924c3b04e47634532ca045f180f755cd2b6e1d5355ede17",
          "sha256": "5dafebd3b04c602e451c80a15b2c0dc7288cd3a9b60ed8195e584b4b02711e79",
          "sha1": "7f2c8dd42f5d5c425b7f982359efea08c5404d6d",
          "md5": "dd16a0ec30a363cb465cb2c680567616"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nfc_manager_release-1.0.0-sources.jar",
          "url": "nfc_manager_release-1.0.0-sources.jar",
          "size": 9778,
          "sha512": "39a2f3ee2aa3d9cd603538d9c7c335a5b052b27eb19d5a9eba206b686c6cdb2730b19b168a499cd06ed40e4b30821474851779e822bf3e9298ef3ba624877844",
          "sha256": "b56d36b34b7a5f9b5395b31a721451d54a82bbae500323355bc8419e21082939",
          "sha1": "482343464b95d4d964aaa5ccfbd550cca4ce8783",
          "md5": "04f583ea11e2643bccab06f24e005bbf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nfc_manager_release-1.0.0-javadoc.jar",
          "url": "nfc_manager_release-1.0.0-javadoc.jar",
          "size": 434316,
          "sha512": "90843f9c635538101a900b7aeb8581a15d031723ff951b2558ecc0dd8d0fa1feeb66962c9e21808a7155bde302798ccc969935d99b66c65fe1774cd4a2fdba95",
          "sha256": "6f20d699397bd570883e571bfa3ee8c0572ee92a50b7c3c580652a9696b40871",
          "sha1": "1a3282df01be30635e794d372b07c09de048d62d",
          "md5": "439ede60c3ca625f4845fc1bf89c750d"
        }
      ]
    }
  ]
}
