{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octmon.flutter_des",
    "module": "flutter_des_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a10d8ac38de835021c8d2f920dbf50a920ccc030"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_des_release-1.0.0.aar",
          "url": "flutter_des_release-1.0.0.aar",
          "size": 3719,
          "sha512": "d9f0d24001de7f589ba422ca8c0d8e769e4f786e14674e1c490227bcd4eec96b72ceee1745d67b515fd740863c774600b7676f79f86a8015684c2b3abe542dee",
          "sha256": "609b31508523b9a2dc8c08051b10c452598176e1ef138d58591b0797670ebee0",
          "sha1": "76886cdc6d1d1ac8ef96463d798ed3683aee89f7",
          "md5": "faa4414a674a3cf07bad0a68156564f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-a10d8ac38de835021c8d2f920dbf50a920ccc030"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_des_release-1.0.0.aar",
          "url": "flutter_des_release-1.0.0.aar",
          "size": 3719,
          "sha512": "d9f0d24001de7f589ba422ca8c0d8e769e4f786e14674e1c490227bcd4eec96b72ceee1745d67b515fd740863c774600b7676f79f86a8015684c2b3abe542dee",
          "sha256": "609b31508523b9a2dc8c08051b10c452598176e1ef138d58591b0797670ebee0",
          "sha1": "76886cdc6d1d1ac8ef96463d798ed3683aee89f7",
          "md5": "faa4414a674a3cf07bad0a68156564f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_des_release-1.0.0-sources.jar",
          "url": "flutter_des_release-1.0.0-sources.jar",
          "size": 2337,
          "sha512": "281ae864a8e16b22fb9991c919117183af8c3f35b8cb4f561ade90931a09b8be51fc2357d2acd1111f03f9ca836581395d3ce128b97751fe3e37f7a82aaa20b7",
          "sha256": "9d477921785e558fffa19009c27cb9d079029e2415958b0e1d993df20ae3ce58",
          "sha1": "0fa95f0e0676da3fd173372e38097278cf6ff97b",
          "md5": "3294a0540b932c47f9789117b4dec4d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_des_release-1.0.0-javadoc.jar",
          "url": "flutter_des_release-1.0.0-javadoc.jar",
          "size": 262059,
          "sha512": "5958340fa91e2d97520c36ebcd45fa3852b398f46323b4844541976f32f873c8f17181c010cc17a2c24bff541c9860108930ba56dba3f63dc5a81fb278d428e8",
          "sha256": "db1b723bfe5f8fc1ca4fc942f0ebe2313c36ab2e5edb6f52fb6bd341496d9df3",
          "sha1": "4300c1942b123cea9df1376ba8f077b079efac1d",
          "md5": "fa6cdbf705727219b462cc8bfc4bdc4f"
        }
      ]
    }
  ]
}
